version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: stylelint
    versions:
    - 13.11.0
    - 13.12.0
    - 13.13.0
  - dependency-name: stylelint-config-recommended
    versions:
    - 4.0.0
